spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  swagger:
    enabled: true
mybatis:
  type-aliases-package: com.felix.springbootdemo.mapper
  configuration:
    #驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
    map-underscore-to-camel-case: true
  #配置xml位置
  #mapper-locations: classpath:com/battcn/mapper/*.xml
logging:
  level:
    com.felix.springbootdemo.mapper: debug
  path: ./logs
pagehelper:
  helper-dialect: postgresql
  params: count
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: false
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
