version: '2'
services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    restart: always
    volumes:
    - /data/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro \
    - /data/openresty/conf.d:/usr/local/openresty/nginx/conf/conf.d \
    - /data/openresty/logs:/usr/local/openresty/nginx/logs \
    - /data/openresty/conf.d:/etc/nginx/conf.d \
    - /data/openresty/ssl:/usr/local/openresty/nginx/ssl \
    - /data/openresty/html:/etc/nginx/html openresty/openresty:alpine
    ports:
    - 8080:80
    - 443:443


  nexus:
    image: sonatype/nexus
    container_name: nexus
    restart: always
    volumes:
    - /some/dir/nexus-data:/nexus-data
    ports:
    -8081:8081


  adminserver:
    image: vmware/harbor-adminserver:__version__
    container_name: harbor-adminserver
    env_file:
    - ./common/config/adminserver/env
    restart: always
    volumes:
    - /data/config/:/etc/adminserver/config/:z
    - /data/secretkey:/etc/adminserver/key:z
    - /data/:/data/:z
    networks:
    - harbor
    depends_on:
    - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:__version__
    container_name: harbor-ui
    env_file:
    - ./common/config/ui/env
    restart: always
    volumes:
    - ./common/config/ui/app.conf:/etc/ui/app.conf:z
    - ./common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
    - ./common/config/ui/certificates/:/etc/ui/certificates/:z
    - /data/secretkey:/etc/ui/key:z
    - /data/ca_download/:/etc/ui/ca/:z
    - /data/psc/:/etc/ui/token/:z
    networks:
    - harbor
    depends_on:
    - log
    - adminserver
    - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:__version__
    container_name: harbor-jobservice
    env_file:
    - ./common/config/jobservice/env
    restart: always
    volumes:
    - /data/job_logs:/var/log/jobs:z
    - ./common/config/jobservice/config.yml:/etc/jobservice/config.yml:z
    networks:
    - harbor
    depends_on:
    - redis
    - ui
    - adminserver
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  redis:
    image: vmware/redis-photon:__redis_version__
    container_name: redis
    restart: always
    volumes:
    - /data/redis:/data
    networks:
    - harbor
    depends_on:
    - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
  proxy:
    image: vmware/nginx-photon:__nginx_version__
    container_name: nginx
    restart: always
    volumes:
    - ./common/config/nginx:/etc/nginx:z
    networks:
    - harbor
    ports:
    - 80:80
    - 443:443
    - 4443:4443
    depends_on:
    - mysql
    - registry
    - ui
    - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false