version: '2'
services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty
    restart: always
    volumes:
    - /data/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro \
    - /data/openresty/conf.d:/usr/local/openresty/nginx/conf/conf.d \
    - /data/openresty/logs:/usr/local/openresty/nginx/logs \
    - /data/openresty/conf.d:/etc/nginx/conf.d \
    - /data/openresty/ssl:/usr/local/openresty/nginx/ssl \
    - /data/openresty/html:/etc/nginx/html openresty/openresty:alpine
    ports:
    - 8080:80
    - 443:443